version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: rollup
    versions:
    - 2.40.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
